[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/cv"
  to = "/downloads/cv.pdf"
  status = 301

[[redirects]]
  from = "/thesis"
  to = "/research"
  status = 301
